/**
 * Built-in Books Service
 *
 * Manages books that ship with the app (Risale-i Nur collection).
 * These books are auto-imported on first launch and cannot be deleted.
 */

import type { Book } from '@/types/book';

// ── Manifest ────────────────────────────────────────────────────────

export interface BuiltinBookEntry {
  /** File path relative to the builtin-books directory */
  filename: string;
  /** Display title in Turkish */
  title: string;
  /** Author */
  author: string;
  /** Language code */
  language: string;
  /** Group for categorization */
  group: 'risale' | 'nur';
  /** Optional: URL to fetch if not available locally */
  url?: string;
  /** Cover image filename (if available) */
  coverFilename?: string;
}

/**
 * Built-in books manifest.
 * Automatically generated by generate_from_markdown.py.
 */
export const BUILTIN_BOOKS: BuiltinBookEntry[] = [
  {
    filename: 'sozler.epub',
    title: 'Sözler',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'mektubat.epub',
    title: 'Mektubat',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'lemalar.epub',
    title: "Lem'alar",
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'sualar.epub',
    title: 'Şuâlar',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'tarihce-i-hayat.epub',
    title: 'Tarihçe-i Hayat',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'mesnevi-i-nuriye.epub',
    title: 'Mesnevî-i Nuriye',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'isaratul-icaz.epub',
    title: "İşaratü'l-i'caz",
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'sikke-i-tasdik-i-gaybi.epub',
    title: 'Sikke-i Tasdik-i Gaybî',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'barla-lahikasi.epub',
    title: 'Barla Lâhikası',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'kastamonu-lahikasi.epub',
    title: 'Kastamonu Lâhikası',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'emirdag-lahikasi-1.epub',
    title: 'Emirdağ Lâhikası 1',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'emirdag-lahikasi-2.epub',
    title: 'Emirdağ Lâhikası 2',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'asa-yi-musa.epub',
    title: 'Asâ-yı Musa',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'muhakemat.epub',
    title: 'Muhakemat',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'risale',
  },
  {
    filename: 'kucuk-kitaplar.epub',
    title: 'Küçük Kitaplar',
    author: 'Bediüzzaman Said Nursi',
    language: 'tr',
    group: 'nur',
  },
  {
    filename: 'ru-kucuk-sozler-parallel.epub',
    title: 'Малые Слова (Параллельный перевод)',
    author: 'Бадиуззаман Саид Нурси',
    language: 'ru',
    group: 'nur',
  },
];

/** URL prefix for fetching builtin books.
 * Must be an absolute URL for the book import pipeline. */
export function getBuiltinBooksBaseUrl(): string {
  if (typeof window !== 'undefined') {
    return `${window.location.origin}/builtin-books`;
  }
  // Fallback for SSR — should be overridden via env var in production
  return process.env['NEXT_PUBLIC_BUILTIN_BOOKS_URL'] || 'http://localhost:3000/builtin-books';
}

/** @deprecated — prefer getBuiltinBooksBaseUrl() */
export const BUILTIN_BOOKS_BASE_URL = '/builtin-books';

// ── Helpers ─────────────────────────────────────────────────────────

/**
 * Check if a book is a built-in book.
 */
export function isBuiltinBook(book: Book): boolean {
  return book.builtin === true;
}

/**
 * Check if a book matches a builtin entry by title.
 */
export function findBuiltinEntry(book: Book): BuiltinBookEntry | undefined {
  return BUILTIN_BOOKS.find(
    (entry) => book.builtin && (book.title === entry.title || book.sourceTitle === entry.filename),
  );
}
